project:
  type: book

book:
  title: "CAS Vegetationsanalyse und Feldbotanik"
  subtitle: "Geografische Kartendarstellung mit R"
  author: "Nils Ratnaweera"
  date: "11/17/2023"
  reader-mode: true
  output-file: "cas-vab-gis"
  downloads: [pdf]
  sidebar: 
    logo: images/zhaw_rgb.png
  chapters:
    - index.qmd
    - uebung_1.qmd
    - uebung_2.qmd
    - uebung_3.qmd
    - uebung_4.qmd
    - uebung_5.qmd
    - uebung_6.qmd

number-depth: 0
number-sections: false
lang: de-CH

execute: 
  freeze: true


format:
  html:
    theme: cosmo
    css: style.css
    include-in-header:
      - script.html
  pdf: default

 

